-- ==============================================================================
-- OLION COFFEE - ENTERPRISE ROW LEVEL SECURITY (RLS) & ANTI-ABUSE MIGRATION
-- Chạy toàn bộ file này trong Supabase Dashboard -> SQL Editor (New Query -> Run)
-- ==============================================================================

-- 1. BẢNG GÓP Ý & ĐÁNH GIÁ (feedbacks)
CREATE TABLE IF NOT EXISTS public.feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Khách ghé quán',
    contact TEXT,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    content TEXT NOT NULL,
    image_url TEXT,
    device_id TEXT,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Đảm bảo cột device_id luôn tồn tại ngay cả khi bảng đã tạo từ trước
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS device_id TEXT;

-- 2. BẢNG VÒNG QUAY MAY MẮN (lucky_spins)
CREATE TABLE IF NOT EXISTS public.lucky_spins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT DEFAULT 'Khách quay minigame',
    customer_phone TEXT NOT NULL,
    prize_name TEXT NOT NULL,
    promo_code TEXT NOT NULL,
    device_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Đảm bảo cột device_id luôn tồn tại ngay cả khi bảng đã tạo từ trước
ALTER TABLE public.lucky_spins ADD COLUMN IF NOT EXISTS device_id TEXT;

-- 3. BẢNG KHÁCH HÀNG & TÍCH ĐIỂM (customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    contact TEXT NOT NULL UNIQUE,
    points INTEGER DEFAULT 0 NOT NULL,
    tier TEXT DEFAULT 'Thành viên' NOT NULL,
    source TEXT DEFAULT 'Website Olion Coffee',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. BẢNG LỊCH SỬ GIAO DỊCH ĐIỂM (point_transactions)
CREATE TABLE IF NOT EXISTS public.point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    customer_contact TEXT NOT NULL,
    action_type TEXT NOT NULL CHECK (action_type IN ('earn', 'redeem', 'adjust')),
    points_change INTEGER NOT NULL,
    balance_after INTEGER NOT NULL DEFAULT 0,
    reason TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. BẢNG QUẢN LÝ THỰC ĐƠN (menu_items)
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    category TEXT NOT NULL DEFAULT 'Cà phê',
    image_url TEXT,
    badge TEXT DEFAULT '',
    description TEXT,
    is_available BOOLEAN DEFAULT TRUE NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- 6. TẠO INDEXES TỐI ƯU HIỆU NĂNG CHO CÁC TRUY VẤN CHECK RATE LIMIT
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_lucky_spins_device_time ON public.lucky_spins (device_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lucky_spins_phone_time ON public.lucky_spins (customer_phone, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedbacks_device_time ON public.feedbacks (device_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedbacks_approved ON public.feedbacks (approved, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customers_contact ON public.customers (contact);

-- ==============================================================================
-- 7. BẬT ROW LEVEL SECURITY (RLS) TRÊN TẤT CẢ CÁC BẢNG
-- ==============================================================================
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lucky_spins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.point_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 8. XÓA CÁC POLICIES CŨ ĐỂ KHÔNG BỊ XUNG ĐỘT
-- ==============================================================================
DROP POLICY IF EXISTS "Public can insert feedback" ON public.feedbacks;
DROP POLICY IF EXISTS "Public can read approved feedbacks" ON public.feedbacks;
DROP POLICY IF EXISTS "Admin full access feedbacks" ON public.feedbacks;
DROP POLICY IF EXISTS "Cho phép khách hàng thêm góp ý" ON public.feedbacks;
DROP POLICY IF EXISTS "Cho phép xem đánh giá đã duyệt" ON public.feedbacks;
DROP POLICY IF EXISTS "Admin toàn quyền feedbacks" ON public.feedbacks;

DROP POLICY IF EXISTS "Public can insert lucky spin" ON public.lucky_spins;
DROP POLICY IF EXISTS "Public can verify own lucky spin" ON public.lucky_spins;
DROP POLICY IF EXISTS "Admin full access lucky spins" ON public.lucky_spins;
DROP POLICY IF EXISTS "Cho phép ghi nhận kết quả quay" ON public.lucky_spins;
DROP POLICY IF EXISTS "Admin toàn quyền lucky_spins" ON public.lucky_spins;

DROP POLICY IF EXISTS "Public can register as customer lead" ON public.customers;
DROP POLICY IF EXISTS "Admin full access customers" ON public.customers;
DROP POLICY IF EXISTS "Cho phép ghi nhận khách hàng" ON public.customers;
DROP POLICY IF EXISTS "Admin toàn quyền customers" ON public.customers;

DROP POLICY IF EXISTS "Admin full access point transactions" ON public.point_transactions;
DROP POLICY IF EXISTS "Public xem point_transactions" ON public.point_transactions;
DROP POLICY IF EXISTS "Admin toàn quyền point_transactions" ON public.point_transactions;

DROP POLICY IF EXISTS "Public can read menu items" ON public.menu_items;
DROP POLICY IF EXISTS "Admin full access menu items" ON public.menu_items;
DROP POLICY IF EXISTS "Public xem menu_items" ON public.menu_items;
DROP POLICY IF EXISTS "Admin toàn quyền menu_items" ON public.menu_items;

-- ==============================================================================
-- 9. THIẾT LẬP CHÍNH SÁCH BẢO MẬT NGHIÊM NGẶT (STRICT POLICIES)
-- ==============================================================================

-- A. BẢNG FEEDBACKS (Góp ý):
-- 1. Khách vãng lai (anon) chỉ được INSERT (Độ dài nội dung >= 3 và <= 2000 ký tự)
CREATE POLICY "Public can insert feedback" ON public.feedbacks
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        LENGTH(content) >= 3 AND LENGTH(content) <= 2000
    );

-- 2. Khách vãng lai CHỈ ĐƯỢC ĐỌC các góp ý đã được duyệt (approved = true)
CREATE POLICY "Public can read approved feedbacks" ON public.feedbacks
    FOR SELECT TO anon, authenticated
    USING (approved = true);

-- 3. Quản trị viên (authenticated) hoặc Service Role toàn quyền (ALL)
CREATE POLICY "Admin full access feedbacks" ON public.feedbacks
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- B. BẢNG LUCKY_SPINS (Vòng quay Minigame):
-- 1. Khách vãng lai chỉ được INSERT lượt quay (SĐT hợp lệ)
CREATE POLICY "Public can insert lucky spin" ON public.lucky_spins
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        LENGTH(customer_phone) >= 8 AND LENGTH(customer_phone) <= 20
    );

-- 2. Khách vãng lai chỉ được SELECT để kiểm tra cooldown của chính thiết bị / SĐT trong 24h
CREATE POLICY "Public can verify own lucky spin" ON public.lucky_spins
    FOR SELECT TO anon, authenticated
    USING (
        created_at >= (now() - INTERVAL '24 hours')
    );

-- 3. Quản trị viên toàn quyền
CREATE POLICY "Admin full access lucky spins" ON public.lucky_spins
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- C. BẢNG CUSTOMERS (Khách hàng & Leads):
-- 1. Khách vãng lai CHỈ được INSERT (Ghi nhận thông tin tham gia minigame / check-in), KHÔNG ĐƯỢC SELECT / UPDATE / DELETE để bảo mật PII
CREATE POLICY "Public can register as customer lead" ON public.customers
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        LENGTH(contact) >= 5
    );

-- 2. Quản trị viên toàn quyền quản lý khách hàng & điểm
CREATE POLICY "Admin full access customers" ON public.customers
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- D. BẢNG POINT_TRANSACTIONS (Lịch sử điểm):
-- 1. Chỉ Quản trị viên mới có quyền xem và ghi sổ điểm
CREATE POLICY "Admin full access point transactions" ON public.point_transactions
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- E. BẢNG MENU_ITEMS (Thực đơn):
DROP POLICY IF EXISTS "Public can read menu items" ON public.menu_items;
DROP POLICY IF EXISTS "Admin full access menu items" ON public.menu_items;
DROP POLICY IF EXISTS "Public xem menu_items" ON public.menu_items;
DROP POLICY IF EXISTS "Admin toàn quyền menu_items" ON public.menu_items;

-- 1. Cho phép đọc công khai toàn bộ món
CREATE POLICY "Public can read menu items" ON public.menu_items
    FOR SELECT TO anon, authenticated, service_role
    USING (true);

-- 2. Cho phép Quản trị viên (hoặc anon từ portal admin) quản lý món
CREATE POLICY "Allow manage menu items" ON public.menu_items
    FOR ALL TO anon, authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- ==============================================================================
-- 10. POSTGRES FUNCTIONS KIỂM TRA CHỐNG SPAM / RATE LIMIT Ở TẦNG DATABASE (RPC)
-- ==============================================================================

-- Function: Kiểm tra điều kiện được phép quay Minigame (24h Cooldown)
CREATE OR REPLACE FUNCTION public.check_can_spin(p_device_id TEXT, p_phone TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_last_spin TIMESTAMP WITH TIME ZONE;
    v_diff_seconds INTEGER;
    v_wait_seconds INTEGER;
BEGIN
    -- Tìm lượt quay gần nhất theo Device ID hoặc Phone trong 24h
    SELECT created_at INTO v_last_spin
    FROM public.lucky_spins
    WHERE (
        (p_device_id IS NOT NULL AND p_device_id <> '' AND device_id = p_device_id)
        OR
        (p_phone IS NOT NULL AND p_phone <> '' AND customer_phone = p_phone)
    )
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_last_spin IS NOT NULL THEN
        v_diff_seconds := EXTRACT(EPOCH FROM (now() - v_last_spin))::INTEGER;
        IF v_diff_seconds < 86400 THEN
            v_wait_seconds := 86400 - v_diff_seconds;
            RETURN json_build_object(
                'can_spin', false,
                'wait_seconds', v_wait_seconds,
                'message', 'Bạn đã sử dụng hết lượt quay hôm nay. Hãy quay lại vào ngày mai nhé!'
            );
        END IF;
    END IF;

    RETURN json_build_object(
        'can_spin', true,
        'wait_seconds', 0,
        'message', 'Được phép quay thưởng!'
    );
END;
$$;

-- Function: Kiểm tra điều kiện gửi Đánh giá / Góp ý (5 phút Cooldown)
CREATE OR REPLACE FUNCTION public.check_can_feedback(p_device_id TEXT, p_contact TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_last_fb TIMESTAMP WITH TIME ZONE;
    v_diff_seconds INTEGER;
    v_wait_seconds INTEGER;
BEGIN
    SELECT created_at INTO v_last_fb
    FROM public.feedbacks
    WHERE (
        (p_device_id IS NOT NULL AND p_device_id <> '' AND device_id = p_device_id)
        OR
        (p_contact IS NOT NULL AND p_contact <> '' AND contact = p_contact)
    )
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_last_fb IS NOT NULL THEN
        v_diff_seconds := EXTRACT(EPOCH FROM (now() - v_last_fb))::INTEGER;
        IF v_diff_seconds < 300 THEN
            v_wait_seconds := 300 - v_diff_seconds;
            RETURN json_build_object(
                'can_submit', false,
                'wait_seconds', v_wait_seconds,
                'message', 'Bạn thao tác quá nhanh! Vui lòng đợi thêm một chút trước khi gửi tiếp.'
            );
        END IF;
    END IF;

    RETURN json_build_object(
        'can_submit', true,
        'wait_seconds', 0,
        'message', 'Được phép gửi góp ý!'
    );
END;
$$;

-- Cấp quyền thực thi RPC cho public/anon
GRANT EXECUTE ON FUNCTION public.check_can_spin(TEXT, TEXT) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_can_feedback(TEXT, TEXT) TO anon, authenticated, service_role;

-- ==============================================================================
-- 11. BẢNG THÀNH VIÊN TÍCH ĐIỂM (loyalty_members)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.loyalty_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL DEFAULT 'Khách hàng thân thiết',
    points INTEGER NOT NULL DEFAULT 0,
    total_visits INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Index tra cứu nhanh số điện thoại
CREATE INDEX IF NOT EXISTS idx_loyalty_members_phone ON public.loyalty_members (phone_number);

-- Bật Row Level Security (RLS)
ALTER TABLE public.loyalty_members ENABLE ROW LEVEL SECURITY;

-- Policies cho bảng loyalty_members:
DROP POLICY IF EXISTS "Public can read loyalty_members" ON public.loyalty_members;
CREATE POLICY "Public can read loyalty_members" ON public.loyalty_members
    FOR SELECT TO anon, authenticated, service_role
    USING (true);

DROP POLICY IF EXISTS "Allow manage loyalty_members" ON public.loyalty_members;
CREATE POLICY "Allow manage loyalty_members" ON public.loyalty_members
    FOR ALL TO anon, authenticated, service_role
    USING (true)
    WITH CHECK (true);

-- Dữ liệu mẫu ban đầu (Seed Data)
INSERT INTO public.loyalty_members (phone_number, customer_name, points, total_visits)
VALUES 
    ('0908123456', 'Nguyễn Minh Anh', 80, 5),
    ('0912334455', 'Trần Hoàng Nam', 35, 2),
    ('0912345678', 'Lê Thanh Trúc', 120, 9),
    ('0978999888', 'Phạm Quốc Bảo', 15, 1)
ON CONFLICT (phone_number) DO UPDATE 
SET points = EXCLUDED.points, total_visits = EXCLUDED.total_visits, updated_at = now();

-- ==============================================================================
-- 12. DỮ LIỆU THỰC ĐƠN CHUẨN 39 MÓN (MENU ITEMS SEED DATA)
-- ==============================================================================
DELETE FROM public.menu_items WHERE id > 0;

INSERT INTO public.menu_items (id, name, price, category, image_url, badge, description, is_available, sort_order)
VALUES
    -- Cà phê
    (1, 'ESPRESSO', 30000, 'Cà phê', 'assets/menu/espresso.webp', '', 'Nóng / Đá. Cà phê nguyên chất đậm đà.', true, 1),
    (2, 'ESPRESSO SỮA', 35000, 'Cà phê', 'assets/menu/espresso_sua.webp', 'BEST', 'Nóng / Đá. Sự kết hợp hoàn hảo giữa espresso và sữa đặc.', true, 2),
    (3, 'BẠC XỈU', 35000, 'Cà phê', 'assets/menu/bac_xiu.webp', 'HOT', 'Nhiều sữa ít cà phê, béo ngậy ngọt ngào.', true, 3),
    (4, 'LATTE HẠNH NHÂN', 40000, 'Cà phê', 'assets/menu/latte_hanh_nhan.webp', '', 'Nóng / Đá. Vị bùi béo của hạnh nhân hòa quyện espresso.', true, 4),
    (5, 'CARAMEL LATTE', 40000, 'Cà phê', 'assets/menu/caramel_latte.webp', '', 'Latte ngọt ngào với lớp sốt caramel thơm lừng.', true, 5),
    (6, 'AMERICANO', 30000, 'Cà phê', 'assets/menu/americano.webp', '', 'Nóng / Đá. Espresso pha loãng thanh tao.', true, 6),
    (7, 'CÀ PHÊ MUỐI', 40000, 'Cà phê', 'assets/menu/ca_phe_muoi.webp', 'SIGNATURE', 'Đậm đà cà phê kết hợp lớp kem muối mặn béo.', true, 7),
    (8, 'CÀ PHÊ BẠC HÀ', 40000, 'Cà phê', 'assets/menu/ca_phe_bac_ha.webp', '', 'Sự the mát sảng khoái của bạc hà và cà phê.', true, 8),
    (9, 'ESPRESSO OATSIDE', 40000, 'Cà phê', 'assets/menu/ca_phe_sua_oatside.webp', 'NEW', 'Nóng / Đá. Sữa yến mạch Oatside kết hợp espresso.', true, 9),

    -- Cacao
    (10, 'CACAO LATTE', 35000, 'Cacao', 'assets/menu/cacao_latte.webp', 'BEST', 'Nóng / Đá. Cacao nguyên chất béo thơm.', true, 10),
    (11, 'CACAO KEM MUỐI', 40000, 'Cacao', 'assets/menu/cacao_kem_muoi.webp', 'HOT', 'Cacao đậm đà hòa quyện lớp kem muối béo ngậy.', true, 11),
    (12, 'CACAO BẠC HÀ', 40000, 'Cacao', 'assets/menu/cacao_bac_ha.webp', '', 'Hương bạc hà the mát sảng khoái quyện cùng vị ngọt đắng cacao.', true, 12),

    -- Trà trái cây
    (13, 'TRÀ VẢI HOA HỒNG', 40000, 'Trà trái cây', 'assets/menu/tra_vai_hoa_hong.webp', 'BEST', 'Vải ngọt mọng nước kết hợp hương hoa hồng thanh tao dịu nhẹ.', true, 13),
    (14, 'TRÀ BƯỞI HỒNG CHANH VÀNG', 40000, 'Trà trái cây', 'assets/menu/tra_buoi_hong_chanh_vang.webp', '', 'Bưởi hồng mọng nước hòa cùng chanh vàng thơm mát.', true, 14),
    (15, 'TRÀ CHANH DÂY NHIỆT ĐỚI', 40000, 'Trà trái cây', 'assets/menu/tra_chanh_day_nhiet_doi.webp', 'HOT', 'Chua ngọt bùng nổ, tươi mát sảng khoái ngày hè.', true, 15),
    (16, 'TRÀ XOÀI CHANH DÂY', 40000, 'Trà trái cây', 'assets/menu/tra_xoai_chanh_day.webp', '', 'Xoài chín ngọt thanh quyện cùng chanh dây đậm đà.', true, 16),
    (17, 'LỤC TRÀ NHÃN', 40000, 'Trà trái cây', 'assets/menu/luc_tra_nhan.webp', '', 'Nhãn giòn ngọt ngào kết hợp nền lục trà lài thanh tao.', true, 17),
    (18, 'LỤC TRÀ TRÂN CHÂU TRẮNG', 35000, 'Trà trái cây', 'assets/menu/luc_tra_tran_chau_trang.webp', '', 'Lục trà lài thanh mát cùng trân châu trắng giòn sần sật.', true, 18),

    -- Nước ép
    (19, 'NƯỚC ÉP CAM', 30000, 'Nước ép', 'assets/menu/nuoc_ep_cam.webp', 'BEST', 'Cam sành tươi vắt nguyên chất, dồi dào Vitamin C.', true, 19),
    (20, 'NƯỚC ÉP CHANH DÂY', 30000, 'Nước ép', 'assets/menu/nuoc_ep_chanh_day.webp', 'HOT', 'Chanh dây tươi thơm nồng, chua ngọt giải nhiệt cực đã.', true, 20),

    -- Trà sữa & Matcha
    (21, 'MATCHA LATTE', 40000, 'Trà sữa & Matcha', 'assets/menu/matcha_latte.webp', 'SIGNATURE', 'Nóng / Đá. Matcha Nhật Bản nguyên chất thơm lừng.', true, 21),
    (22, 'MATCHA CARAMEL', 45000, 'Trà sữa & Matcha', 'assets/menu/matcha_caramel.webp', '', 'Matcha thơm đậm hòa quyện cùng sốt caramel béo ngậy.', true, 22),
    (23, 'MATCHA BẠC HÀ', 45000, 'Trà sữa & Matcha', 'assets/menu/matcha_bac_ha.webp', '', 'Sự kết hợp độc đáo giữa vị thanh của matcha và the mát của bạc hà.', true, 23),
    (24, 'MATCHA KEM MUỐI', 45000, 'Trà sữa & Matcha', 'assets/menu/matcha_kem_muoi.webp', '', 'Lớp kem muối béo ngậy mằn mặn phủ trên nền matcha đậm đà.', true, 24),
    (25, 'MATCHA QUẾ HOA', 45000, 'Trà sữa & Matcha', 'assets/menu/matcha_que_hoa.webp', '', 'Matcha cao cấp ướp hương hoa quế tự nhiên thanh tao.', true, 25),
    (26, 'MATCHA COLD WHISK', 45000, 'Trà sữa & Matcha', 'assets/menu/matcha_cold_whisk.webp', '', 'Nóng / Đá. Đánh bọt matcha lạnh thủ công truyền thống.', true, 26),
    (27, 'MATCHA DỪA', 45000, 'Trà sữa & Matcha', 'assets/menu/matcha_dua.webp', '', 'Vị thơm bùi của nước cốt dừa tươi quyện cùng bột matcha thượng hạng.', true, 27),
    (28, 'MATCHA DÂU', 45000, 'Trà sữa & Matcha', 'assets/menu/matcha_dau.webp', 'HOT', 'Sự hòa quyện tuyệt hảo giữa matcha thơm đắng và mứt dâu tây.', true, 28),
    (29, 'MATCHA ESPRESSO LATTE', 45000, 'Trà sữa & Matcha', 'assets/menu/matcha_oatside.webp', '', 'Kết hợp hoàn hảo giữa Matcha và Espresso Latte.', true, 29),

    -- Sữa chua
    (30, 'YAGOUT ĐÀO CHANH DÂY', 45000, 'Sữa chua', 'assets/menu/yagout_dao_chanh_day.webp', '', 'Đào mọng nước thơm ngọt hòa cùng vị chua dịu nhẹ của chanh dây.', true, 30),
    (31, 'YAGOUT VIỆT QUẤT', 45000, 'Sữa chua', 'assets/menu/yagout_viet_quat.webp', 'HOT', 'Việt quất bổ dưỡng thơm lừng quyện cùng sữa chua tươi mát.', true, 31),
    (32, 'YAGOUT XOÀI CHANH DÂY', 45000, 'Sữa chua', 'assets/menu/yagout_xoai_chanh_day.webp', '', 'Xoài chín thơm ngọt hòa quyện cùng chanh dây nhiệt đới.', true, 32),
    (33, 'YAGOUT DÂU', 45000, 'Sữa chua', 'assets/menu/yagout_dau.webp', 'BEST', 'Sữa chua sánh mịn kết hợp mứt dâu tây chua ngọt thanh mát.', true, 33),

    -- Topping
    (34, 'TRÂN CHÂU TRẮNG', 5000, 'Topping', 'assets/menu/tran_chau_trang.webp', '', 'Trân châu trắng ngọc trai giòn dai thơm ngon.', true, 34),
    (35, 'TRÂN CHÂU Ô LONG', 5000, 'Topping', 'assets/menu/tran_chau_o_long.webp', '', 'Đậm hương trà ô long rang mộc, mềm dẻo.', true, 35),
    (36, 'THẠCH SƯƠNG SÁO', 5000, 'Topping', 'assets/menu/thach_suong_sao.webp', '', 'Thạch sương sáo mềm mượt, thanh mát giải nhiệt tự nhiên.', true, 36),
    (37, 'THẠCH QUẾ HOA', 5000, 'Topping', 'assets/menu/thach_que_hoa.webp', '', 'Thơm thanh hương hoa quế tự nhiên.', true, 37),
    (38, 'THẠCH VẢI HOA HỒNG', 5000, 'Topping', 'assets/menu/thach_vai_hoa_hong.webp', '', 'Thạch giòn dai thơm ngát hương hoa hồng và vị vải ngọt thanh.', true, 38),
    (39, 'THẠCH CÀ PHÊ', 5000, 'Topping', 'assets/menu/thach_ca_phe.webp', '', 'Thạch cà phê nấu thủ công giòn thơm đậm vị.', true, 39);

-- ==============================================================================
-- BẢNG: news_items (Quản lý Tin Tức & Sự Kiện)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.news_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    category TEXT NOT NULL,
    cover_image TEXT NOT NULL,
    description TEXT,
    content_html TEXT,
    is_featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bật RLS
ALTER TABLE public.news_items ENABLE ROW LEVEL SECURITY;

-- Policy: Ai cũng có thể xem tin tức
DROP POLICY IF EXISTS "Allow read news_items" ON public.news_items;
CREATE POLICY "Allow read news_items" ON public.news_items
    FOR SELECT TO anon, authenticated, service_role
    USING (true);

-- Policy: Chỉ định quyền quản lý (Thêm/Sửa/Xóa) cho ẩn danh (tạm thời)
DROP POLICY IF EXISTS "Allow manage news_items" ON public.news_items;
CREATE POLICY "Allow manage news_items" ON public.news_items
    FOR ALL TO anon, authenticated, service_role
    USING (true)
    WITH CHECK (true);

-- Dữ liệu mẫu
INSERT INTO public.news_items (title, date, category, cover_image, description, content_html, is_featured)
VALUES 
('OLION’S FIRST WEEK — NHẬT KÝ TUẦN ĐẦU TIÊN', '19/09/2026', 'Sự kiện đặc biệt', 'assets/news/news-1-flowers.webp', 'Tuần đầu tiên mở cửa đã khép lại với biết bao cung bậc cảm xúc! Olion Coffee vô cùng trân trọng...', '<p>Tuần đầu tiên mở cửa đã khép lại với biết bao cung bậc cảm xúc! Olion Coffee vô cùng trân trọng và biết ơn những lẵng hoa tươi thắm, những lời chúc mừng chân thành từ quý đối tác, bạn bè và đặc biệt là sự ủng hộ nhiệt tình của hàng trăm lượt khách hàng đã ghé thăm quán mỗi ngày.</p><p>Mỗi ly cà phê trao đi là một lời cảm ơn sâu sắc. Chúng tôi cam kết sẽ tiếp tục hoàn thiện không gian và chất lượng đồ uống để mang đến những trải nghiệm tuyệt vời nhất cho bạn.</p>', true),

('Khám Phá Bộ Đôi Matcha Latte & Cà Phê Muối Chuẩn Vị', '18/09/2026', 'Thực Đơn Signature', 'assets/news/news-1-drinks.webp', 'Tại Olion Coffee, mỗi ly thức uống đều được pha chế bằng cả sự nâng niu và tỉ mỉ. Lớp bọt kem muối béo mặn...', '<p>Tại Olion Coffee, mỗi ly thức uống đều được pha chế bằng cả sự nâng niu và tỉ mỉ.</p><div class="news-quote-box">"Lớp bọt kem muối béo mặn sánh mịn hòa cùng cốt cà phê đậm đà tạo nên hương vị bùng nổ ngay từ ngụm đầu tiên."</div><p>Bên cạnh đó, dòng Matcha Latte sử dụng 100% bột trà xanh nhập khẩu từ Shizuoka Nhật Bản, mang hương thơm thanh nhã và vị đắng dịu êm ái.</p>', true),

('Góc Yên Bình Giữa Lòng Gò Vấp Cho Những Buổi Chiều Làm Việc', '15/09/2026', 'Không Gian Quán', 'assets/news/news-1-space.webp', 'Bước qua cánh cửa Olion, bạn sẽ cảm nhận ngay một không gian tách biệt khỏi nhịp sống vội vã ngoài phố thị...', '<p>Bước qua cánh cửa Olion, bạn sẽ cảm nhận ngay một không gian tách biệt khỏi nhịp sống vội vã ngoài phố thị.</p><p>Tông màu gỗ ấm cúng, hệ thống đèn lồng giấy dịu mắt cùng những chậu cây xanh mướt tạo nên một chốn dừng chân hoàn hảo để đọc sách, làm việc hay trò chuyện cùng bạn bè.</p>', true),

('Grand Opening Recap — Tuần Lễ Khai Trương Rực Rỡ Ưu Đãi', '12/09/2026', 'Chương Trình Khuyến Mãi', 'assets/news/news-1-recap.webp', 'Nhìn lại những khoảnh khắc tuyệt vời trong tuần lễ Grand Opening! Khách hàng không chỉ được thưởng thức...', '<p>Nhìn lại những khoảnh khắc tuyệt vời trong tuần lễ Grand Opening! Khách hàng không chỉ được thưởng thức menu giảm giá 20% mà còn nhận được hàng trăm phần quà thú vị từ Vòng Quay May Mắn.</p><p>Đừng quên Olion Coffee vẫn đang áp dụng chương trình Tích điểm Loyalty: 10 ly tặng 1 ly hoàn toàn miễn phí nhé!</p>', true);
