-- ==============================================================================
-- OLION COFFEE - SUPABASE CLOUD DATABASE SCHEMA MIGRATION (IDEMPOTENT & SAFE)
-- Chạy toàn bộ file này trong SQL Editor trên Supabase Dashboard (Bấm New Query -> Dán toàn bộ -> Nhấn Run)
-- ==============================================================================

-- 1. TẠO BẢNG ĐÁNH GIÁ & GÓP Ý (feedbacks)
CREATE TABLE IF NOT EXISTS public.feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Khách ghé quán',
    contact TEXT,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    content TEXT NOT NULL,
    image_url TEXT,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TẠO BẢNG VÒNG QUAY MAY MẮN (lucky_spins)
CREATE TABLE IF NOT EXISTS public.lucky_spins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT DEFAULT 'Khách quay minigame',
    customer_phone TEXT NOT NULL,
    prize_name TEXT NOT NULL,
    promo_code TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TẠO BẢNG KHÁCH HÀNG TIỀM NĂNG (customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    contact TEXT NOT NULL,
    source TEXT DEFAULT 'Website Olion Coffee',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. BẬT ROW LEVEL SECURITY (RLS)
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lucky_spins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- 5. XÓA POLICY CŨ NẾU ĐÃ TỒN TẠI ĐỂ TRÁNH TRÙNG LẶP
DROP POLICY IF EXISTS "Cho phép khách hàng thêm góp ý" ON public.feedbacks;
DROP POLICY IF EXISTS "Cho phép xem đánh giá đã duyệt" ON public.feedbacks;
DROP POLICY IF EXISTS "Admin toàn quyền feedbacks" ON public.feedbacks;
DROP POLICY IF EXISTS "Cho phép ghi nhận kết quả quay" ON public.lucky_spins;
DROP POLICY IF EXISTS "Admin toàn quyền lucky_spins" ON public.lucky_spins;
DROP POLICY IF EXISTS "Cho phép ghi nhận khách hàng" ON public.customers;
DROP POLICY IF EXISTS "Admin toàn quyền customers" ON public.customers;

-- 6. TẠO POLICIES MỚI
CREATE POLICY "Cho phép khách hàng thêm góp ý" ON public.feedbacks
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Cho phép xem đánh giá đã duyệt" ON public.feedbacks
    FOR SELECT USING (approved = true);

CREATE POLICY "Admin toàn quyền feedbacks" ON public.feedbacks
    FOR ALL USING (true);

CREATE POLICY "Cho phép ghi nhận kết quả quay" ON public.lucky_spins
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin toàn quyền lucky_spins" ON public.lucky_spins
    FOR ALL USING (true);

CREATE POLICY "Cho phép ghi nhận khách hàng" ON public.customers
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Admin toàn quyền customers" ON public.customers
    FOR ALL USING (true);

-- 7. BẬT REALTIME AN TOÀN (Không gây lỗi nếu bảng đã được thêm từ trước)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'feedbacks'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.feedbacks;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'lucky_spins'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.lucky_spins;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'customers'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.customers;
    END IF;
END $$;

-- 8. THÊM DỮ LIỆU MẪU BAN ĐẦU (Chỉ thêm nếu bảng feedbacks còn trống)
INSERT INTO public.feedbacks (name, contact, rating, content, approved)
SELECT 'Minh Anh', 'minhanh.vlu@gmail.com', 5, 'Quán nằm trong hẻm yên tĩnh ở Dương Quảng Hàm, bước vào cảm giác như tách biệt khỏi xô bồ ngoài kia. Đèn vàng ấm mắt, bàn ghế gỗ cao ngồi làm việc cả buổi rất thoải mái. Cà phê muối béo mặn cực kỳ vừa miệng!', true
WHERE NOT EXISTS (SELECT 1 FROM public.feedbacks LIMIT 1);

INSERT INTO public.feedbacks (name, contact, rating, content, approved)
SELECT 'Thanh Trúc', '0908123456', 5, 'Matcha latte ở đây chuẩn vị Nhật, thơm đắng thanh nhẹ và không bị ngọt gắt như nhiều chỗ khác. Tụi mình hay ghé đây đọc sách và trò chuyện cuối tuần vì nhạc mở vừa phải rất dễ chịu.', true
WHERE (SELECT COUNT(*) FROM public.feedbacks) = 1;

INSERT INTO public.feedbacks (name, contact, rating, content, approved)
SELECT 'Hoàng Nam', 'hoangnam.freelance@gmail.com', 5, 'Bạc xỉu kem trứng ngon đỉnh chóp! Lớp bọt trứng béo mịn uống tới đâu dính tới đó. Nhân viên thân thiện, nhiệt tình châm trà liên tục. Chắc chắn sẽ là quán ruột của mình.', true
WHERE (SELECT COUNT(*) FROM public.feedbacks) = 2;
