-- ==============================================================================
-- OLION COFFEE - SUPABASE CLOUD DATABASE SCHEMA MIGRATION
-- Chạy script này trong mục SQL Editor trên trang Supabase Dashboard của bạn
-- ==============================================================================

-- 1. BẢNG ĐÁNH GIÁ & GÓP Ý (feedbacks)
CREATE TABLE IF NOT EXISTS public.feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Khách ghé quán',
    contact TEXT,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    content TEXT NOT NULL,
    image_url TEXT,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. BẢNG VÒNG QUAY MAY MẮN (lucky_spins)
CREATE TABLE IF NOT EXISTS public.lucky_spins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT DEFAULT 'Khách quay minigame',
    customer_phone TEXT NOT NULL,
    prize_name TEXT NOT NULL,
    promo_code TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. BẢNG KHÁCH HÀNG TIỀM NĂNG / LEADS (customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    contact TEXT NOT NULL,
    source TEXT DEFAULT 'Website Olion Coffee',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- BẬT ROW LEVEL SECURITY (RLS)
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lucky_spins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- CẤP QUYỀN CHO PUBLIC TRÊN WEB ĐỂ THÊM VÀ XEM DỮ LIỆU
-- Cho phép khách hàng gửi đánh giá
CREATE POLICY "Cho phép khách hàng thêm góp ý" ON public.feedbacks
    FOR INSERT WITH CHECK (true);

-- Cho phép khách hàng đọc đánh giá đã được duyệt
CREATE POLICY "Cho phép xem đánh giá đã duyệt" ON public.feedbacks
    FOR SELECT USING (approved = true);

-- Cho phép khách hàng ghi nhận vòng quay may mắn
CREATE POLICY "Cho phép ghi nhận kết quả quay" ON public.lucky_spins
    FOR INSERT WITH CHECK (true);

-- Cho phép ghi nhận khách hàng mới
CREATE POLICY "Cho phép ghi nhận khách hàng" ON public.customers
    FOR INSERT WITH CHECK (true);

-- Cho phép Admin (toàn quyền) thao tác khi dùng Anon Key cấu hình
CREATE POLICY "Admin toàn quyền feedbacks" ON public.feedbacks
    FOR ALL USING (true);

CREATE POLICY "Admin toàn quyền lucky_spins" ON public.lucky_spins
    FOR ALL USING (true);

CREATE POLICY "Admin toàn quyền customers" ON public.customers
    FOR ALL USING (true);

-- BẬT REALTIME CHO CÁC BẢNG (để trang admin cập nhật dữ liệu trực tiếp)
ALTER PUBLICATION supabase_realtime ADD TABLE public.feedbacks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.lucky_spins;
ALTER PUBLICATION supabase_realtime ADD TABLE public.customers;

-- CHÈN DỮ LIỆU MẪU ĐÁNH GIÁ BAN ĐẦU
INSERT INTO public.feedbacks (name, contact, rating, content, approved) VALUES
('Minh Anh', 'minhanh.vlu@gmail.com', 5, 'Quán nằm trong hẻm yên tĩnh ở Dương Quảng Hàm, bước vào cảm giác như tách biệt khỏi xô bồ ngoài kia. Đèn vàng ấm mắt, bàn ghế gỗ cao ngồi làm việc cả buổi rất thoải mái. Cà phê muối béo mặn cực kỳ vừa miệng!', true),
('Thanh Trúc', '0908123456', 5, 'Matcha latte ở đây chuẩn vị Nhật, thơm đắng thanh nhẹ và không bị ngọt gắt như nhiều chỗ khác. Tụi mình hay ghé đây đọc sách và trò chuyện cuối tuần vì nhạc mở vừa phải rất dễ chịu.', true),
('Hoàng Nam', 'hoangnam.freelance@gmail.com', 5, 'Bạc xỉu kem trứng ngon đỉnh chóp! Lớp bọt trứng béo mịn uống tới đâu dính tới đó. Nhân viên thân thiện, nhiệt tình châm trà liên tục. Chắc chắn sẽ là quán ruột của mình.', true);
