-- ==============================================================================
-- OLION COFFEE - ENTERPRISE ROW LEVEL SECURITY (RLS) & ANTI-ABUSE MIGRATION
-- Chạy toàn bộ file này trong Supabase Dashboard -> SQL Editor (New Query -> Run)
-- ==============================================================================

-- 1. BẢNG GÓP Ý & ĐÁNH GIÁ (feedbacks)
CREATE TABLE IF NOT EXISTS public.feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL DEFAULT 'Khách ghé quán',
    contact TEXT,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    content TEXT NOT NULL,
    image_url TEXT,
    device_id TEXT,
    approved BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bổ sung cột device_id nếu chưa có
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='feedbacks' AND column_name='device_id') THEN
        ALTER TABLE public.feedbacks ADD COLUMN device_id TEXT;
    END IF;
END $$;

-- 2. BẢNG VÒNG QUAY MAY MẮN (lucky_spins)
CREATE TABLE IF NOT EXISTS public.lucky_spins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name TEXT DEFAULT 'Khách quay minigame',
    customer_phone TEXT NOT NULL,
    prize_name TEXT NOT NULL,
    promo_code TEXT NOT NULL,
    device_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bổ sung cột device_id nếu chưa có
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='lucky_spins' AND column_name='device_id') THEN
        ALTER TABLE public.lucky_spins ADD COLUMN device_id TEXT;
    END IF;
END $$;

-- 3. BẢNG KHÁCH HÀNG & TÍCH ĐIỂM (customers)
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT,
    contact TEXT NOT NULL UNIQUE,
    points INTEGER DEFAULT 0 NOT NULL,
    tier TEXT DEFAULT 'Thành viên' NOT NULL,
    source TEXT DEFAULT 'Website Olion Coffee',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. BẢNG LỊCH SỬ GIAO DỊCH ĐIỂM (point_transactions)
CREATE TABLE IF NOT EXISTS public.point_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    customer_contact TEXT NOT NULL,
    action_type TEXT NOT NULL CHECK (action_type IN ('earn', 'redeem', 'adjust')),
    points_change INTEGER NOT NULL,
    balance_after INTEGER NOT NULL DEFAULT 0,
    reason TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. BẢNG QUẢN LÝ THỰC ĐƠN (menu_items)
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    category TEXT NOT NULL DEFAULT 'Cà phê',
    image_url TEXT,
    badge TEXT DEFAULT '',
    description TEXT,
    is_available BOOLEAN DEFAULT TRUE NOT NULL,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ==============================================================================
-- 6. TẠO INDEXES TỐI ƯU HIỆU NĂNG CHO CÁC TRUY VẤN CHECK RATE LIMIT
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_lucky_spins_device_time ON public.lucky_spins (device_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lucky_spins_phone_time ON public.lucky_spins (customer_phone, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedbacks_device_time ON public.feedbacks (device_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feedbacks_approved ON public.feedbacks (approved, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_customers_contact ON public.customers (contact);

-- ==============================================================================
-- 7. BẬT ROW LEVEL SECURITY (RLS) TRÊN TẤT CẢ CÁC BẢNG
-- ==============================================================================
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lucky_spins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.point_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 8. XÓA CÁC POLICIES CŨ ĐỂ KHÔNG BỊ XUNG ĐỘT
-- ==============================================================================
DROP POLICY IF EXISTS "Public can insert feedback" ON public.feedbacks;
DROP POLICY IF EXISTS "Public can read approved feedbacks" ON public.feedbacks;
DROP POLICY IF EXISTS "Admin full access feedbacks" ON public.feedbacks;
DROP POLICY IF EXISTS "Cho phép khách hàng thêm góp ý" ON public.feedbacks;
DROP POLICY IF EXISTS "Cho phép xem đánh giá đã duyệt" ON public.feedbacks;
DROP POLICY IF EXISTS "Admin toàn quyền feedbacks" ON public.feedbacks;

DROP POLICY IF EXISTS "Public can insert lucky spin" ON public.lucky_spins;
DROP POLICY IF EXISTS "Public can verify own lucky spin" ON public.lucky_spins;
DROP POLICY IF EXISTS "Admin full access lucky spins" ON public.lucky_spins;
DROP POLICY IF EXISTS "Cho phép ghi nhận kết quả quay" ON public.lucky_spins;
DROP POLICY IF EXISTS "Admin toàn quyền lucky_spins" ON public.lucky_spins;

DROP POLICY IF EXISTS "Public can register as customer lead" ON public.customers;
DROP POLICY IF EXISTS "Admin full access customers" ON public.customers;
DROP POLICY IF EXISTS "Cho phép ghi nhận khách hàng" ON public.customers;
DROP POLICY IF EXISTS "Admin toàn quyền customers" ON public.customers;

DROP POLICY IF EXISTS "Admin full access point transactions" ON public.point_transactions;
DROP POLICY IF EXISTS "Public xem point_transactions" ON public.point_transactions;
DROP POLICY IF EXISTS "Admin toàn quyền point_transactions" ON public.point_transactions;

DROP POLICY IF EXISTS "Public can read menu items" ON public.menu_items;
DROP POLICY IF EXISTS "Admin full access menu items" ON public.menu_items;
DROP POLICY IF EXISTS "Public xem menu_items" ON public.menu_items;
DROP POLICY IF EXISTS "Admin toàn quyền menu_items" ON public.menu_items;

-- ==============================================================================
-- 9. THIẾT LẬP CHÍNH SÁCH BẢO MẬT NGHIÊM NGẶT (STRICT POLICIES)
-- ==============================================================================

-- A. BẢNG FEEDBACKS (Góp ý):
-- 1. Khách vãng lai (anon) chỉ được INSERT (Độ dài nội dung >= 3 và <= 2000 ký tự)
CREATE POLICY "Public can insert feedback" ON public.feedbacks
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        LENGTH(content) >= 3 AND LENGTH(content) <= 2000
    );

-- 2. Khách vãng lai CHỈ ĐƯỢC ĐỌC các góp ý đã được duyệt (approved = true)
CREATE POLICY "Public can read approved feedbacks" ON public.feedbacks
    FOR SELECT TO anon, authenticated
    USING (approved = true);

-- 3. Quản trị viên (authenticated) hoặc Service Role toàn quyền (ALL)
CREATE POLICY "Admin full access feedbacks" ON public.feedbacks
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- B. BẢNG LUCKY_SPINS (Vòng quay Minigame):
-- 1. Khách vãng lai chỉ được INSERT lượt quay (SĐT hợp lệ)
CREATE POLICY "Public can insert lucky spin" ON public.lucky_spins
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        LENGTH(customer_phone) >= 8 AND LENGTH(customer_phone) <= 20
    );

-- 2. Khách vãng lai chỉ được SELECT để kiểm tra cooldown của chính thiết bị / SĐT trong 24h
CREATE POLICY "Public can verify own lucky spin" ON public.lucky_spins
    FOR SELECT TO anon, authenticated
    USING (
        created_at >= (now() - INTERVAL '24 hours')
    );

-- 3. Quản trị viên toàn quyền
CREATE POLICY "Admin full access lucky spins" ON public.lucky_spins
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- C. BẢNG CUSTOMERS (Khách hàng & Leads):
-- 1. Khách vãng lai CHỈ được INSERT (Ghi nhận thông tin tham gia minigame / check-in), KHÔNG ĐƯỢC SELECT / UPDATE / DELETE để bảo mật PII
CREATE POLICY "Public can register as customer lead" ON public.customers
    FOR INSERT TO anon, authenticated
    WITH CHECK (
        LENGTH(contact) >= 5
    );

-- 2. Quản trị viên toàn quyền quản lý khách hàng & điểm
CREATE POLICY "Admin full access customers" ON public.customers
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- D. BẢNG POINT_TRANSACTIONS (Lịch sử điểm):
-- 1. Chỉ Quản trị viên mới có quyền xem và ghi sổ điểm
CREATE POLICY "Admin full access point transactions" ON public.point_transactions
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- E. BẢNG MENU_ITEMS (Thực đơn):
-- 1. Khách vãng lai CHỈ được xem món đang mở bán (SELECT)
CREATE POLICY "Public can read menu items" ON public.menu_items
    FOR SELECT TO anon, authenticated
    USING (true);

-- 2. Quản trị viên toàn quyền CRUD món
CREATE POLICY "Admin full access menu items" ON public.menu_items
    FOR ALL TO authenticated, service_role
    USING (true)
    WITH CHECK (true);


-- ==============================================================================
-- 10. POSTGRES FUNCTIONS KIỂM TRA CHỐNG SPAM / RATE LIMIT Ở TẦNG DATABASE (RPC)
-- ==============================================================================

-- Function: Kiểm tra điều kiện được phép quay Minigame (24h Cooldown)
CREATE OR REPLACE FUNCTION public.check_can_spin(p_device_id TEXT, p_phone TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_last_spin TIMESTAMP WITH TIME ZONE;
    v_diff_seconds INTEGER;
    v_wait_seconds INTEGER;
BEGIN
    -- Tìm lượt quay gần nhất theo Device ID hoặc Phone trong 24h
    SELECT created_at INTO v_last_spin
    FROM public.lucky_spins
    WHERE (
        (p_device_id IS NOT NULL AND p_device_id <> '' AND device_id = p_device_id)
        OR
        (p_phone IS NOT NULL AND p_phone <> '' AND customer_phone = p_phone)
    )
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_last_spin IS NOT NULL THEN
        v_diff_seconds := EXTRACT(EPOCH FROM (now() - v_last_spin))::INTEGER;
        IF v_diff_seconds < 86400 THEN
            v_wait_seconds := 86400 - v_diff_seconds;
            RETURN json_build_object(
                'can_spin', false,
                'wait_seconds', v_wait_seconds,
                'message', 'Bạn đã sử dụng hết lượt quay hôm nay. Hãy quay lại vào ngày mai nhé!'
            );
        END IF;
    END IF;

    RETURN json_build_object(
        'can_spin', true,
        'wait_seconds', 0,
        'message', 'Được phép quay thưởng!'
    );
END;
$$;

-- Function: Kiểm tra điều kiện gửi Đánh giá / Góp ý (5 phút Cooldown)
CREATE OR REPLACE FUNCTION public.check_can_feedback(p_device_id TEXT, p_contact TEXT)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_last_fb TIMESTAMP WITH TIME ZONE;
    v_diff_seconds INTEGER;
    v_wait_seconds INTEGER;
BEGIN
    SELECT created_at INTO v_last_fb
    FROM public.feedbacks
    WHERE (
        (p_device_id IS NOT NULL AND p_device_id <> '' AND device_id = p_device_id)
        OR
        (p_contact IS NOT NULL AND p_contact <> '' AND contact = p_contact)
    )
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_last_fb IS NOT NULL THEN
        v_diff_seconds := EXTRACT(EPOCH FROM (now() - v_last_fb))::INTEGER;
        IF v_diff_seconds < 300 THEN
            v_wait_seconds := 300 - v_diff_seconds;
            RETURN json_build_object(
                'can_submit', false,
                'wait_seconds', v_wait_seconds,
                'message', 'Bạn thao tác quá nhanh! Vui lòng đợi thêm một chút trước khi gửi tiếp.'
            );
        END IF;
    END IF;

    RETURN json_build_object(
        'can_submit', true,
        'wait_seconds', 0,
        'message', 'Được phép gửi góp ý!'
    );
END;
$$;

-- Cấp quyền thực thi RPC cho public/anon
GRANT EXECUTE ON FUNCTION public.check_can_spin(TEXT, TEXT) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_can_feedback(TEXT, TEXT) TO anon, authenticated, service_role;
