-- ==============================================================================
-- OLION COFFEE - BẢNG KIẾN THỨC HUẤN LUYỆN TRỢ LÝ AI BARISTA (ai_context)
-- Thực thi mã này trong Supabase Dashboard -> SQL Editor (New query -> Run)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.ai_context (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    context_text TEXT NOT NULL,
    updated_by TEXT DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bật Row Level Security (RLS)
ALTER TABLE public.ai_context ENABLE ROW LEVEL SECURITY;

-- Cho phép khách hàng công khai đọc kiến thức AI để chatbot hoạt động
DROP POLICY IF EXISTS "Public can read ai_context" ON public.ai_context;
CREATE POLICY "Public can read ai_context" ON public.ai_context
    FOR SELECT
    USING (true);

-- Cho phép người dùng công khai hoặc admin thêm/cập nhật kiến thức AI
DROP POLICY IF EXISTS "Public can update ai_context" ON public.ai_context;
CREATE POLICY "Public can update ai_context" ON public.ai_context
    FOR ALL
    USING (true);

-- Khởi tạo dữ liệu kiến thức cơ sở ban đầu cho AI Barista
INSERT INTO public.ai_context (id, context_text, updated_by)
VALUES (
    1,
    'Olion Coffee tọa lạc tại 80/64A Dương Quảng Hàm, An Nhơn, Gò Vấp, TP. Hồ Chí Minh. Hotline đặt hàng & giao hàng: 0783 657 587. Giờ mở cửa: 08:00 - 21:00 hàng ngày (kể cả Lễ, Tết). Quán có không gian đèn vàng ấm cúng, bàn ghế gỗ cao ngồi làm việc thoải mái, nhiều ổ cắm điện, wifi tốc độ cao và nhạc acoustic êm dịu. Món Signature đặc sắc nhất: Cà Phê Muối Olion (39k), Bạc Xỉu Kem Trứng (42k), và Japanese Matcha Latte (39k). Quán sử dụng 100% hạt cà phê Robusta & Arabica Cầu Đất rang mộc nguyên chất, bột Matcha nhập khẩu từ Nhật Bản và sữa hạt yến mạch Oatside cho người ăn kiêng. Hiện quán đang có chương trình Vòng quay may mắn trúng mã giảm giá từ 10% đến tặng 1 ly nước!',
    'admin'
)
ON CONFLICT (id) DO UPDATE 
SET context_text = EXCLUDED.context_text,
    updated_at = timezone('utc'::text, now());
