-- ==============================================================================
-- OLION COFFEE - BẢNG KHÁCH HÀNG (CUSTOMERS LEAD GENERATION)
-- Thực thi mã này trong Supabase Dashboard -> SQL Editor (New query -> Run)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT NOT NULL UNIQUE, -- Số điện thoại định danh khách hàng
    points INTEGER DEFAULT 0 NOT NULL,
    tier TEXT DEFAULT 'Thành viên' NOT NULL,
    source TEXT DEFAULT 'Smart Welcome Popup',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tạo Index tìm kiếm nhanh theo số điện thoại
CREATE INDEX IF NOT EXISTS idx_customers_contact ON public.customers (contact);

-- Bật Row Level Security (RLS)
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

-- Cho phép khách hàng từ Web công khai đăng ký (Insert / Upsert Lead)
DROP POLICY IF EXISTS "Public can register as customer lead" ON public.customers;
CREATE POLICY "Public can register as customer lead" ON public.customers
    FOR INSERT
    WITH CHECK (true);

-- Cho phép Admin toàn quyền quản lý bảng khách hàng
DROP POLICY IF EXISTS "Admin full access customers" ON public.customers;
CREATE POLICY "Admin full access customers" ON public.customers
    FOR ALL
    USING (auth.role() = 'authenticated');
